name: Windows CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MSYS2 (GCC)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-gcc
          make
          mingw-w64-x86_64-pkg-config

    - name: Create bin directory
      run: mkdir .bin

    - name: Compile unit tests
      shell: msys2 {0}
      run: |
        gcc -Wall -Wextra \
        tests/unitTest.c \
        tests/Unity/*.c \
        tests/unitTests/*.c \
        directive/*.c \
        -Iunity \
        -lbcrypt \
        -luser32 \
        -o .bin/unitTests.exe

    - name: Run unit tests
      shell: msys2 {0}
      run: ./.bin/unitTests.exe